# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# ==============================================================================
# LiteRT-LM Abseil Target-to-Path Mapping
# ==============================================================================
set(LITERTLM_ABSL_TARGET_MAP
    "absl::base=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_base${LITERTLM_STATIC_LIB_EXT}"
    "absl::base_cpu_detect=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_base_cpu_detect${LITERTLM_STATIC_LIB_EXT}"
    "absl::city=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_city${LITERTLM_STATIC_LIB_EXT}"
    "absl::civil_time=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_civil_time${LITERTLM_STATIC_LIB_EXT}"
    "absl::clock_interface=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_clock_interface${LITERTLM_STATIC_LIB_EXT}"
    "absl::cord=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_cord${LITERTLM_STATIC_LIB_EXT}"
    "absl::cord_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_cord_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::cordz_functions=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_cordz_functions${LITERTLM_STATIC_LIB_EXT}"
    "absl::cordz_handle=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_cordz_handle${LITERTLM_STATIC_LIB_EXT}"
    "absl::cordz_info=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_cordz_info${LITERTLM_STATIC_LIB_EXT}"
    "absl::cordz_sample_token=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_cordz_sample_token${LITERTLM_STATIC_LIB_EXT}"
    "absl::crc32c=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_crc32c${LITERTLM_STATIC_LIB_EXT}"
    "absl::crc_cord_state=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_crc_cord_state${LITERTLM_STATIC_LIB_EXT}"
    "absl::crc_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_crc_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::debugging_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_debugging_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::decode_rust_punycode=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_decode_rust_punycode${LITERTLM_STATIC_LIB_EXT}"
    "absl::demangle_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_demangle_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::demangle_rust=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_demangle_rust${LITERTLM_STATIC_LIB_EXT}"
    "absl::die_if_null=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_die_if_null${LITERTLM_STATIC_LIB_EXT}"
    "absl::examine_stack=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_examine_stack${LITERTLM_STATIC_LIB_EXT}"
    "absl::exponential_biased=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_exponential_biased${LITERTLM_STATIC_LIB_EXT}"
    "absl::failure_signal_handler=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_failure_signal_handler${LITERTLM_STATIC_LIB_EXT}"
    "absl::flags_commandlineflag=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_flags_commandlineflag${LITERTLM_STATIC_LIB_EXT}"
    "absl::flags_commandlineflag_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_flags_commandlineflag_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::flags_config=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_flags_config${LITERTLM_STATIC_LIB_EXT}"
    "absl::flags_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_flags_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::flags_marshalling=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_flags_marshalling${LITERTLM_STATIC_LIB_EXT}"
    "absl::flags_parse=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_flags_parse${LITERTLM_STATIC_LIB_EXT}"
    "absl::flags_private_handle_accessor=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_flags_private_handle_accessor${LITERTLM_STATIC_LIB_EXT}"
    "absl::flags_program_name=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_flags_program_name${LITERTLM_STATIC_LIB_EXT}"
    "absl::flags_reflection=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_flags_reflection${LITERTLM_STATIC_LIB_EXT}"
    "absl::flags_usage=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_flags_usage${LITERTLM_STATIC_LIB_EXT}"
    "absl::flags_usage_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_flags_usage_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::generic_printer_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_generic_printer_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::graphcycles_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_graphcycles_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::hardening=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_hardening${LITERTLM_STATIC_LIB_EXT}"
    "absl::hash=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_hash${LITERTLM_STATIC_LIB_EXT}"
    "absl::hashtable_profiler=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_hashtable_profiler${LITERTLM_STATIC_LIB_EXT}"
    "absl::hashtablez_sampler=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_hashtablez_sampler${LITERTLM_STATIC_LIB_EXT}"
    "absl::int128=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_int128${LITERTLM_STATIC_LIB_EXT}"
    "absl::kernel_timeout_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_kernel_timeout_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::leak_check=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_leak_check${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_entry=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_entry${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_flags=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_flags${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_globals=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_globals${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_initialize=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_initialize${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_internal_check_op=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_internal_check_op${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_internal_conditions=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_internal_conditions${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_internal_fnmatch=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_internal_fnmatch${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_internal_format=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_internal_format${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_internal_globals=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_internal_globals${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_internal_log_sink_set=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_internal_log_sink_set${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_internal_message=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_internal_message${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_internal_nullguard=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_internal_nullguard${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_internal_proto=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_internal_proto${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_internal_structured_proto=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_internal_structured_proto${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_severity=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_severity${LITERTLM_STATIC_LIB_EXT}"
    "absl::log_sink=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_log_sink${LITERTLM_STATIC_LIB_EXT}"
    "absl::malloc_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_malloc_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::periodic_sampler=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_periodic_sampler${LITERTLM_STATIC_LIB_EXT}"
    "absl::poison=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_poison${LITERTLM_STATIC_LIB_EXT}"
    "absl::profile_builder=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_profile_builder${LITERTLM_STATIC_LIB_EXT}"
    "absl::random_distributions=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_random_distributions${LITERTLM_STATIC_LIB_EXT}"
    "absl::random_internal_distribution_test_util=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_random_internal_distribution_test_util${LITERTLM_STATIC_LIB_EXT}"
    "absl::random_internal_entropy_pool=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_random_internal_entropy_pool${LITERTLM_STATIC_LIB_EXT}"
    "absl::random_internal_platform=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_random_internal_platform${LITERTLM_STATIC_LIB_EXT}"
    "absl::random_internal_randen=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_random_internal_randen${LITERTLM_STATIC_LIB_EXT}"
    "absl::random_internal_randen_hwaes=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_random_internal_randen_hwaes${LITERTLM_STATIC_LIB_EXT}"
    "absl::random_internal_randen_hwaes_impl=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_random_internal_randen_hwaes_impl${LITERTLM_STATIC_LIB_EXT}"
    "absl::random_internal_randen_slow=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_random_internal_randen_slow${LITERTLM_STATIC_LIB_EXT}"
    "absl::random_internal_seed_material=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_random_internal_seed_material${LITERTLM_STATIC_LIB_EXT}"
    "absl::random_seed_gen_exception=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_random_seed_gen_exception${LITERTLM_STATIC_LIB_EXT}"
    "absl::random_seed_sequences=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_random_seed_sequences${LITERTLM_STATIC_LIB_EXT}"
    "absl::raw_hash_set=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_raw_hash_set${LITERTLM_STATIC_LIB_EXT}"
    "absl::raw_logging_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_raw_logging_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::scoped_set_env=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_scoped_set_env${LITERTLM_STATIC_LIB_EXT}"
    "absl::source_location=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_source_location${LITERTLM_STATIC_LIB_EXT}"
    "absl::spinlock_wait=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_spinlock_wait${LITERTLM_STATIC_LIB_EXT}"
    "absl::stacktrace=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_stacktrace${LITERTLM_STATIC_LIB_EXT}"
    "absl::status=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_status${LITERTLM_STATIC_LIB_EXT}"
    "absl::status_builder=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_status_builder${LITERTLM_STATIC_LIB_EXT}"
    "absl::statusor=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_statusor${LITERTLM_STATIC_LIB_EXT}"
    "absl::str_format_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_str_format_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::strerror=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_strerror${LITERTLM_STATIC_LIB_EXT}"
    "absl::strings=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_strings${LITERTLM_STATIC_LIB_EXT}"
    "absl::strings_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_strings_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::symbolize=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_symbolize${LITERTLM_STATIC_LIB_EXT}"
    "absl::synchronization=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_synchronization${LITERTLM_STATIC_LIB_EXT}"
    "absl::throw_delegate=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_throw_delegate${LITERTLM_STATIC_LIB_EXT}"
    "absl::time=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_time${LITERTLM_STATIC_LIB_EXT}"
    "absl::time_zone=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_time_zone${LITERTLM_STATIC_LIB_EXT}"
    "absl::tracing_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_tracing_internal${LITERTLM_STATIC_LIB_EXT}"
    "absl::utf8_for_code_point=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_utf8_for_code_point${LITERTLM_STATIC_LIB_EXT}"
    "absl::vlog_config_internal=${LITERTLM_ABSL_LIB_DIR}/${LITERTLM_LIB_PREFIX}absl_vlog_config_internal${LITERTLM_STATIC_LIB_EXT}"
    CACHE INTERNAL "Mapping of Abseil targets to their corresponding library paths"
)